### ISSUE TITLE
Implement Dark/Inverted style

### ISSUE THREAD

**Issue by luksireiku** [KingPixil/wing#43]
I would love to use the css styles but with inverted color scheme, would it be hard to implement?

**Comment by KingPixil** [comment]
Hey!

Overriding a style made by Wing is easy, and would be similar to how you'd accomplish it with other frameworks. Just style elements you want to be a different color with plain CSS (after you've loaded Wing).

For example:

```css
h1, h2, h3, h4, h5, p, {
  color: white;
}
button {
  background: white;
   color: white;
}
```

Also, for buttons, Wing provides styles such as `btn btn-outline` that allow support for darker color schemes.
